### ISSUE TITLE
Credits due

### ISSUE THREAD

**Issue by FinalPacket** [thatmadhacker/Freezer#1]
You need to give some credit to the original creator :)
(not me, TheWoosh)

**Comment by thatmadhacker** [comment]
Who is the original creator?

**Comment by FinalPacket** [comment]
Ain't nice stealing code for speed checks, nofall checks, checkresult.
If I stole your plugin right now and said I made it, how would you feel?

You added a command and a config, well done! Still not yours now is it.

**Comment by thatmadhacker** [comment]
You know that having a CheckResult class is one of the most generic things in Minecraft anti cheats? You would have a hard time finding an anti cheat that does not use it. My no fall check also is not at all similar to any other no fall code I have seen, and my speed code is written almost completely by me with a little bit of help from the constants from NoCheatPlus. Your claims are ridiculous and I will not be responding to any more comments you make on this issue.

**Comment by ElementalRealm** [comment]
Hello guys and girls. I passed here to say that this plugin is property of Epic Realms Inc. and the creator is thatmadhacker. We have the legal rights on the plugin since the creator work for us.

What you are doing is difamating a brend and that is not legal. Thatmadhacker is licensed by Epic Realms Inc. and we would thanks this doesnt repeat. If you have any doubts I can make you bein in touch with our lawyers office to show you the creating license.
Thanks and have a nice day.
